[package]
name = "gsd"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gsd-sys = { git = "https://github.com/ianrgraham/gsd-sys.git" }
